import Navigation from '@/components/common/header/navigation/navigation';

export const metadata = {
  title: 'Smuk Nu',
  description: 'Generated by create next app',
};

export default function siteLayout({ children }) {
  return (
    <div>
      <Navigation logo={'smuknu_logo.png'} />
      {children}
    </div>
  );
}
